### ISSUE TITLE
The endless "Joining world..."

### ISSUE THREAD

**Issue by lastickss** [tupini07/minecraft-forge-mod-example-kotlin#1]
Pls, help. When I enter the world, there is an endless "Joining world...". I did not edit any files, I did everything according to the instructions.

![image](https://github.com/tupini07/minecraft-forge-mod-example-kotlin/assets/96003586/9df789ac-f6b6-4ff2-ba5e-19981f130059)

Here's what it says in the console:

[console.txt](https://github.com/tupini07/minecraft-forge-mod-example-kotlin/files/15062909/console.txt)

**Comment by tupini07** [comment]
Hi! Sorry about this, I was playing with how to inspect the packets sent from client to server and never finished that part or removed it 😅 

I've just pushed a [commit](https://github.com/tupini07/minecraft-forge-mod-example-kotlin/commit/c4eb445f5304350840ab9658bd49e59549bdf675) that comments out the related code in `ClientEventListener`. Let me know if this fixes your issue.

I really need to clean this up (and maybe write a proper readme?) since right now it works but it's quite "messy"

**Comment by lastickss** [comment]
I'm sorry I took so long. Everything is working, thanks!

**Comment by tupini07** [comment]
No worries 🙂 I'm happy to hear it's all working now
